### ISSUE TITLE
IsolateException

### ISSUE THREAD

**Issue by liweiGe** [vnniz/isolate_manager#6]
if compute api run too many times，can throw this excepotion
num = 1000000000
<img width="389" alt="image" src="https://github.com/vnniz/isolate_manager/assets/25901728/c8a8831d-2539-4e17-b75a-3124806b8428">

<img width="1237" alt="image" src="https://github.com/vnniz/isolate_manager/assets/25901728/f8ac5da9-8a78-4e42-9705-4845e9031065">
<img width="699" alt="image" src="https://github.com/vnniz/isolate_manager/assets/25901728/b7b3aabb-52f5-4cac-9b95-ba72479a74be">

**Comment by vnniz** [comment]
Hello @liweiGe 

I just run a simple test on this case but it run as expected:
<img width="580" alt="image" src="https://github.com/vnniz/isolate_manager/assets/91940731/b7beff7a-7cd2-48de-af59-8f91402591b1">

Please give me the code that caused that issue so I can easier to resolve it.

**Comment by liweiGe** [comment]
you need have a page, and just only have a button,on the OnPress to done this action,must click frequent and fast
<img width="726" alt="image" src="https://github.com/vnniz/isolate_manager/assets/25901728/1e4917d3-0521-4b25-a141-9419fb004d96">

**Comment by vnniz** [comment]
The issue is resolved in version `3.0.1`. Please give it a try and let me know the result.

Thanks for your report.
