### ISSUE TITLE
数据长度比较大时，并发不执行

### ISSUE THREAD

**Issue by shijia2118** [vnniz/isolate_manager#7]
void main() {
  runApp(const MyApp());
final isolateManager = IsolateManager.create(
    concurrent: 50,
    isoLateBlurImage,
    isDebug: true,
  );
}

@pragma('vm:entry-point')
void isoLateBlurImage(List<String> imageList) async {
  for (var url in imageList) {
    final blurImage = await opencv.calculateImageBlur(imageUrl: url);
  }
}
当imageList超过80时，并发无法执行。

**Comment by vnniz** [comment]
Hi @shijia2118 

Have you tried to decrease the number of concurrent? 50 Isolates are a bit too much I think, it may cause out of memory issue.

**Comment by shijia2118** [comment]
Thank you for your reply! I tried to set concurrent to 10, but the result was the same.

**Comment by shijia2118** [comment]
Hi @vnniz 
Even if concurrent is set to 5, concurrency cannot be executed. However, when the length of the imageList is reduced to less than 60, the program executes normally.

**Comment by vnniz** [comment]
Hi @shijia2118 

I'm trying to create a simple script that sends a List with 100 elements and it runs normally, so I think that another thing causes the issue:

``` dart
import 'package:isolate_manager/isolate_manager.dart';

void main() async {
  final isolateManager = IsolateManager.create(
    concurrent: 5,
    some,
    isDebug: true,
  );

  isolateManager.compute([
    for (int i = 0; i < 100; i++)
      'assddwdqwdbqkbfkwebckjeqbckjbqkjcbkjbckjqbwckjbqkjcbwkjedbckjbewckjwebckjbkjcbwekjbckjwebkjcbwekj'
  ]);
}

void some(List list) {}
```

However, I think the best way to do the thing that you wanted is that creating a function that only processes 1 URL, then you can send multiple URLs to it and let it automatically queues the URLs.

For instance:

``` dart
void main() async {
  final isolateManager = IsolateManager.create(
    concurrent: 5,
    processURL,
    isDebug: true,
  );

  for (int i = 0; i < 100; i++) {
    isolateManager.compute(
      'https://example.com/abc',
    );
  }
}

Future<void> processURL(String url) async {
  final blurImage = await opencv.calculateImageBlur(imageUrl: url);
}
```

**Comment by shijia2118** [comment]
Thank you very much for your detailed guidance. Now I will test it according to your logic.

**Comment by shijia2118** [comment]
Finally found the root of the problem. The reason for this is the plugin I use, image_picker. When the image_picker plugin selects too many images at once, the plugin stops working, causing data to fail to reach the isolate. This is independent of isolate_manager. On the contrary, isolate_manager works perfectly, thank you very much!

**Comment by vnniz** [comment]
Thank you. I'll close this issue as it has been resolved.
